name: hplip-twosky2000 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: New hplip drivers for HP Printers & Scanners # 79 char long summary
description: |
  Package for hplib, HP drivers for printers and scanners.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  hplip-twosky2000:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://datapacket.dl.sourceforge.net/project/hplip/hplip/3.19.1/hplip-3.19.1.tar.gz
    override-build: |
      snapcraftctl build
      cp /root/parts/hplip-twosky2000/build/prnt/hpcups/libImageProcessor.so /root/parts/hplip-twosky2000/install/lib/
    #  cp /root/parts/hplip-twosky2000/build/prnt/hpcups/libImageProcessor-x86_32.so /root/prime/usr/lib/
    #  cp /root/parts/hplip-twosky2000/build/prnt/hpcups/libImageProcessor-x86_64.so /root/prime/usr/lib/
    configflags: 
      - --with-hpppddir=/usr/share/ppd/HP
      - --libdir=/usr/lib64
      - --enable-qt4
      - --enable-qt5
      - --enable-libusb01_build
      - --enable-doc-build
      - --enable-cups-ppd-install
      - --disable-foomatic-drv-install
      - --disable-foomatic-ppd-install
      - --disable-hpijs-install
      - --disable-udev_sysfs_rules
      - --disable-policykit
      - --disable-cups-drv-install
      - --enable-hpcups-install
      - --enable-network-build
      - --enable-dbus-build
      - --enable-scan-build
      - --enable-fax-build

    stage-packages:
      - libusb-1.0-0
      #- libImageProcessor
      - libavahi-client3
      - libavahi-common3
      - libcups2
      - libcupsimage2
      #- libieee1284
      - libjpeg9
      - libsnmp-base
      - libsane
      - python
      - libsnmp30
      - python-qt4
      - python-pyqt5
      - python-dbus
      - python-gobject
      - python-notify
      - python-reportlab
      - python-pil

      
    build-packages:
      - g++
      - make
      - libcups2-dev
      - cups-bsd
      - cups-client
      - libusb-1.0-0-dev
      - libtool
      - libtool-bin
      - libcupsimage2-dev
      - libjpeg-dev
      - openssl
      - libssl-dev
      - libsnmp-dev
      - snmp-mibs-downloader
      - python-qt4-dbus
      - gtk2-engines-pixbuf
      - libdbus-1-dev
      - libsane-dev
      - python-dev
      - python-qt4
      - python-dbus
      - python-gobject
      - python-notify
      - python-reportlab
      - python-pil

apps:
  hp-info:
    command: usr/bin/hp-info
  hp-print:
    command: usr/bin/hp-print
  hp-scan:
    command: usr/bin/hp-scan
  hp-testpage:
    command: usr/bin/hp-testpage
  hp-setup:
    command: usr/bin/hp-setup
